name: Standard Notes Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-18.04
         
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Build and test with Rake
        run: |
          gem install bundler && bundle install

  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
      - name: Build
        run: docker build -t syncing-server .
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
         name: jeroenpardon/syncing-server
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }}
